{
	'name':'univercity',
	'version':'1.0',
	'category':'Sales',
	'sequence':120,
	'summary':'UniverCity Module',
	'description':"""Online admission unvercity portal
	""",
	'website':'https://www.browseinfo.in',
	'depends':['sale'],
	'data':[
		'wizard/univercity_wizard_inquiry_views.xml',
		'wizard/student_create_password_views.xml',
		# 'wizard/student_app_report_views.xml',
		# 'report/inquiry_report_views.xml',
		'views/univercity_inquiry_details_views.xml',
		'views/univercity_education_stream_views.xml',
		'views/univercity_club_views.xml',
		'views/univercity_qualification_rules_views.xml',
		'views/univercity_student_achievement_views.xml',
		'views/univercity_library_management_views.xml',
		'views/univercity_courses_views.xml',
		'views/univercity_application_details_views.xml', 
		'views/univercity_book_issues_views.xml',
		],
	'demo':[],
	'css':[],
	'installable': True,
	'auto_install': False,
	'application': False,
}